site_name: CESNET Models
repo_name: CESNET/cesnet-models
repo_url: https://github.com/CESNET/cesnet-models

theme:
  name: "material"
  palette:
    primary: blue grey
  features:
    - navigation.sections
  logo: images/models_logo.svg
  favicon: images/models_logo.svg

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [cesnet_models]

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  analytics:
    provider: google
    property: G-788ETHG59K

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Tutorials:
    - Getting started: getting_started.md
  - Reference:
    - Pre-trained models: reference_models.md
    - Transforms: reference_transforms.md
